from __future__ import annotations

CATEGORY_LABELS = {
    1: "Gênero principal",
    2: "Mecânica relevante",
    3: "Característica técnica",
    4: "Estilo/estética",
    5: "Irrelevante para similaridade estrutural",
}


GENERO_PRINCIPAL = {
    "2D Fighter",
    "2D Platformer",
    "3D Fighter",
    "3D Platformer",
    "4X",
    "Action",
    "Action RPG",
    "Action RTS",
    "Action Roguelike",
    "Action-Adventure",
    "Adventure",
    "Arcade",
    "Arena Shooter",
    "Auto Battler",
    "Automobile Sim",
    "Beat 'em up",
    "Board Game",
    "Bullet Hell",
    "CRPG",
    "Card Battler",
    "Card Game",
    "Character Action Game",
    "City Builder",
    "Clicker",
    "Colony Sim",
    "Dating Sim",
    "Dungeon Crawler",
    "Escape Room",
    "Farming Sim",
    "Fighting",
    "Flight",
    "FPS",
    "God Game",
    "Grand Strategy",
    "Hack and Slash",
    "Hidden Object",
    "Hobby Sim",
    "Horror",
    "Idler",
    "Immersive Sim",
    "Interactive Fiction",
    "JRPG",
    "Job Simulator",
    "Life Sim",
    "Logic",
    "Looter Shooter",
    "MMORPG",
    "MOBA",
    "Match 3",
    "Medical Sim",
    "Metroidvania",
    "Music",
    "Mystery Dungeon",
    "Musou",
    "On-Rails Shooter",
    "Open World Survival Craft",
    "Otome",
    "Outbreak Sim",
    "Party Game",
    "Party-Based RPG",
    "Pinball",
    "Platformer",
    "Point & Click",
    "Precision Platformer",
    "Puzzle",
    "Puzzle Platformer",
    "RPG",
    "RTS",
    "Racing",
    "Rhythm",
    "Roguelike",
    "Roguelike Deckbuilder",
    "Roguelite",
    "Roguevania",
    "Runner",
    "Shoot 'Em Up",
    "Shooter",
    "Simulation",
    "Sokoban",
    "Solitaire",
    "Souls-like",
    "Space Sim",
    "Spectacle fighter",
    "Sports",
    "Strategy",
    "Strategy RPG",
    "Survival",
    "Survival Horror",
    "Tabletop",
    "Tactical RPG",
    "Third-Person Shooter",
    "Tower Defense",
    "Trading Card Game",
    "Traditional Roguelike",
    "Trivia",
    "Turn-Based Strategy",
    "Turn-Based Tactics",
    "Twin Stick Shooter",
    "Vehicular Combat",
    "Visual Novel",
    "Walking Simulator",
    "Wargame",
    "Wrestling",
    "Word Game",
}


MECANICA_RELEVANTE = {
    "4 Player Local",
    "6DOF",
    "Asynchronous Multiplayer",
    "Automation",
    "Base Building",
    "Building",
    "Bullet Time",
    "Character Customization",
    "Choices Matter",
    "Choose Your Own Adventure",
    "Class-Based",
    "Co-op",
    "Co-op Campaign",
    "Collectathon",
    "Combat",
    "Competitive",
    "Conversation",
    "Cooking",
    "Crafting",
    "Creature Collector",
    "Deckbuilding",
    "Destruction",
    "Diplomacy",
    "Driving",
    "Economy",
    "Exploration",
    "Fishing",
    "Grid-Based Movement",
    "Gun Customization",
    "Hacking",
    "Hex Grid",
    "Inventory Management",
    "Linear",
    "Local Co-Op",
    "Local Multiplayer",
    "Loot",
    "Management",
    "Massively Multiplayer",
    "Minigames",
    "Multiplayer",
    "Multiple Endings",
    "Nonlinear",
    "Online Co-Op",
    "Open World",
    "Parkour",
    "Perma Death",
    "Physics",
    "Procedural Generation",
    "PvE",
    "PvP",
    "Quick-Time Events",
    "Real Time Tactics",
    "Real-Time",
    "Real-Time with Pause",
    "Resource Management",
    "Sandbox",
    "Score Attack",
    "Shop Keeper",
    "Singleplayer",
    "Social Deduction",
    "Stealth",
    "Tactical",
    "Team-Based",
    "Time Attack",
    "Time Management",
    "Time Manipulation",
    "Trading",
    "Turn-Based",
    "Turn-Based Combat",
    "Typing",
}


CARACTERISTICA_TECNICA = {
    "2.5D",
    "2D",
    "3D",
    "360 Video",
    "3D Vision",
    "Asymmetric VR",
    "Controller",
    "First-Person",
    "FMV",
    "Isometric",
    "Mouse only",
    "Side Scroller",
    "Split Screen",
    "Steam Machine",
    "Text-Based",
    "Third Person",
    "Top-Down",
    "Touch-Friendly",
    "TrackIR",
    "VR",
    "Voice Control",
}


ESTILO_ESTETICA = {
    "8-bit Music",
    "Abstract",
    "Ambient",
    "Anime",
    "Atmospheric",
    "Beautiful",
    "Cartoon",
    "Cartoony",
    "Cinematic",
    "Cozy",
    "Colorful",
    "Comic Book",
    "Cute",
    "Dark",
    "Dark Comedy",
    "Dark Humor",
    "Emotional",
    "Experimental",
    "Funny",
    "Gothic",
    "Hand-drawn",
    "Lovecraftian",
    "Minimalist",
    "Noir",
    "Old School",
    "Philosophical",
    "Pixel Graphics",
    "Psychedelic",
    "Psychological",
    "Realistic",
    "Relaxing",
    "Retro",
    "Steampunk",
    "Stylized",
    "Surreal",
    "Thriller",
    "Voxel",
    "Wholesome",
}


IRRELEVANTE = {
    "1980s",
    "1990's",
    "ATV",
    "Addictive",
    "Agriculture",
    "Aliens",
    "Alternate History",
    "America",
    "Animation & Modeling",
    "Archery",
    "Artificial Intelligence",
    "Assassin",
    "Audio Production",
    "BMX",
    "Baseball",
    "Based On A Novel",
    "Basketball",
    "Battle Royale",
    "Benchmark",
    "Bikes",
    "Blood",
    "Boss Rush",
    "Bowling",
    "Boxing",
    "Capitalism",
    "Casual",
    "Cats",
    "Chess",
    "Coding",
    "Cold War",
    "Classic",
    "Combat Racing",
    "Comedy",
    "Conspiracy",
    "Crime",
    "Cricket",
    "Crowdfunded",
    "Cult Classic",
    "Cyberpunk",
    "Cycling",
    "Dark Fantasy",
    "Demons",
    "Design & Illustration",
    "Detective",
    "Difficult",
    "Dinosaurs",
    "Documentary",
    "Dog",
    "Dragons",
    "Drama",
    "Dungeons & Dragons",
    "Dynamic Narration",
    "Dystopian",
    "Early Access",
    "Education",
    "Electronic",
    "Electronic Music",
    "Epic",
    "Episodic",
    "Experience",
    "Faith",
    "Family Friendly",
    "Fantasy",
    "Farming",
    "Fast-Paced",
    "Feature Film",
    "Female Protagonist",
    "Football (American)",
    "Football (Soccer)",
    "Foreign",
    "Fox",
    "Free to Play",
    "Futuristic",
    "Gambling",
    "Game Development",
    "GameMaker",
    "Games Workshop",
    "Gaming",
    "Golf",
    "Gore",
    "Great Soundtrack",
    "Hardware",
    "Heist",
    "Hentai",
    "Hero Shooter",
    "Historical",
    "Hockey",
    "Horses",
    "Hunting",
    "Illuminati",
    "Immersive",
    "Indie",
    "Instrumental Music",
    "Intentionally Awkward Controls",
    "Investigation",
    "Jet",
    "Jump Scare",
    "Kickstarter",
    "LEGO",
    "LGBTQ+",
    "Lemmings",
    "Level Editor",
    "Lore-Rich",
    "Magic",
    "Mahjong",
    "Mars",
    "Martial Arts",
    "Mature",
    "Mechs",
    "Medieval",
    "Memes",
    "Military",
    "Mini Golf",
    "Mining",
    "Mod",
    "Moddable",
    "Modern",
    "Motocross",
    "Motorbike",
    "Movie",
    "Music-Based Procedural Generation",
    "Mystery",
    "Mythology",
    "NSFW",
    "Narration",
    "Narrative",
    "Nature",
    "Naval",
    "Naval Combat",
    "Ninja",
    "Nostalgia",
    "Nudity",
    "Offroad",
    "Parody",
    "Party",
    "Photo Editing",
    "Pirates",
    "Political",
    "Political Sim",
    "Politics",
    "Pool",
    "Post-apocalyptic",
    "Programming",
    "Psychological Horror",
    "RPGMaker",
    "Reboot",
    "Remake",
    "Replay Value",
    "Robots",
    "Rock Music",
    "Romance",
    "Rome",
    "Rugby",
    "Sailing",
    "Satire",
    "Sci-fi",
    "Science",
    "Sequel",
    "Sexual Content",
    "Short",
    "Silent Protagonist",
    "Skateboarding",
    "Skating",
    "Skiing",
    "Sniper",
    "Snooker",
    "Snow",
    "Snowboarding",
    "Software",
    "Software Training",
    "Soundtrack",
    "Space",
    "Spaceships",
    "Spelling",
    "Submarine",
    "Superhero",
    "Supernatural",
    "Story Rich",
    "Swordplay",
    "Tanks",
    "Tennis",
    "Tile-Matching",
    "Time Travel",
    "Top-Down Shooter",
    "Trains",
    "Transhumanism",
    "Transportation",
    "Tutorial",
    "Underground",
    "Underwater",
    "Unforgiving",
    "Utilities",
    "Vampire",
    "Video Production",
    "Vikings",
    "Villain Protagonist",
    "Violent",
    "Volleyball",
    "War",
    "Warhammer 40K",
    "Web Publishing",
    "Well-Written",
    "Werewolves",
    "Western",
    "World War I",
    "World War II",
    "Zombies",
    "eSports",
}


def build_tag_categories():
    category_to_tags = {
        1: GENERO_PRINCIPAL,
        2: MECANICA_RELEVANTE,
        3: CARACTERISTICA_TECNICA,
        4: ESTILO_ESTETICA,
        5: IRRELEVANTE,
    }

    seen = {}
    for category_id, tags in category_to_tags.items():
        for tag in tags:
            if tag in seen:
                raise ValueError(f"Tag duplicada em categorias diferentes: {tag!r}")
            seen[tag] = category_id
    return seen


TAG_CATEGORIES = build_tag_categories()
