MIN_TAG_FREQ = 50
MAX_TAG_PERCENT = 0.15


# Normalizacao conservadora:
# - corrige apenas sinonimos claros, abreviacoes e variacoes ortograficas
# - evita colapsar subgeneros que podem formar comunidades proprias
TAG_NORMALIZATION = {
    # Abreviacoes e nomes canonicos
    "First-Person Shooter": "FPS",
    "RTS": "Real-Time Strategy",
    "Real Time Tactics": "Real-Time Tactics",
    "Deckbuilding": "Deckbuilder",
    "Football (Soccer)": "Football",

    # Variacoes de caixa / grafia observadas no dataset
    "Mouse only": "Mouse Only",
}


# Tags protegidas do filtro de alta frequencia e do corte por raridade.
# A ideia aqui e preservar:
# - generos principais
# - subgeneros estruturais relevantes
# - mecanicas com poder discriminativo real para o grafo jogo-jogo
ALWAYS_KEEP_TAGS = {
    # Generos amplos
    "Action",
    "Adventure",
    "RPG",
    "Strategy",
    "Simulation",
    "Shooter",
    "Platformer",
    "Puzzle",
    "Survival",
    "Sports",
    "Racing",
    "Fighting",
    "Visual Novel",

    # Hibridos e estruturas amplas
    "Action-Adventure",
    "Sandbox",
    "Management",
    "Building",
    "Crafting",
    "Stealth",
    "Tactical",
    "Turn-Based",
    "Turn-Based Combat",
    "Resource Management",
    "Logic",
    "Board Game",
    "Tabletop",
    "Clicker",
    "Idler",
    "Auto Battler",
    "Automation",
    "Collectathon",
    "Inventory Management",
    "Grid-Based Movement",
    "Hex Grid",
    "Trading",
    "Economy",
    "Social Deduction",

    # Shooter
    "FPS",
    "Third-Person Shooter",
    "Top-Down Shooter",
    "Twin Stick Shooter",
    "Arena Shooter",
    "Hero Shooter",
    "Looter Shooter",
    "On-Rails Shooter",
    "Shoot 'Em Up",
    "Bullet Hell",
    "MOBA",

    # Platforming
    "2D Platformer",
    "3D Platformer",
    "Precision Platformer",
    "Puzzle Platformer",
    "Metroidvania",
    "Side Scroller",
    "Runner",

    # RPG
    "Action RPG",
    "JRPG",
    "CRPG",
    "Party-Based RPG",
    "Strategy RPG",
    "Tactical RPG",
    "Dungeon Crawler",
    "Creature Collector",
    "Character Action Game",
    "Souls-like",

    # Strategy
    "Real-Time Strategy",
    "Turn-Based Strategy",
    "Grand Strategy",
    "4X",
    "Tower Defense",
    "Wargame",
    "Real-Time Tactics",
    "Turn-Based Tactics",
    "God Game",
    "Action RTS",

    # Simulation / builders
    "Life Sim",
    "Dating Sim",
    "Farming Sim",
    "City Builder",
    "Colony Sim",
    "Immersive Sim",
    "Automobile Sim",
    "Space Sim",
    "Open World Survival Craft",
    "Outbreak Sim",
    "Base Building",
    "Medical Sim",

    # Roguelike family
    "Roguelike",
    "Roguelite",
    "Traditional Roguelike",
    "Action Roguelike",
    "Roguevania",
    "Mystery Dungeon",
    "Roguelike Deckbuilder",

    # Card / deck
    "Card Game",
    "Deckbuilder",
    "Card Battler",
    "Trading Card Game",
    "Solitaire",

    # Adventure subgenres
    "Point & Click",
    "Interactive Fiction",
    "Walking Simulator",
    "Hidden Object",
    "Escape Room",

    # Outros estruturais
    "Survival Horror",
    "Football",
    "Football (American)",
    "Basketball",
    "Golf",
    "Boxing",
    "Pinball",
    "Combat Racing",
    "Vehicular Combat",
    "Flight",
}


# Blacklist orientada ao objetivo do projeto:
# remover tags que descrevem tema, estetica, audiencia, plataforma,
# metadados editoriais ou modos de jogo muito genericos.
TAGS_TO_REMOVE = {
    # Modos de jogo / multiplayer generico
    "Singleplayer",
    "Multiplayer",
    "Co-op",
    "Online Co-Op",
    "Local Co-Op",
    "Local Multiplayer",
    "Massively Multiplayer",
    "MMORPG",
    "PvP",
    "PvE",
    "4 Player Local",
    "Asynchronous Multiplayer",
    "Co-op Campaign",
    "Party Game",
    "Party",
    "Team-Based",
    "Competitive",
    "Battle Royale",
    "eSports",
    "Class-Based",

    # Tecnicas / plataforma / interface
    "2D",
    "3D",
    "2.5D",
    "First-Person",
    "Third Person",
    "Controller",
    "Mouse Only",
    "VR",
    "Asymmetric VR",
    "TrackIR",
    "Touch-Friendly",
    "3D Vision",
    "Steam Machine",
    "6DOF",

    # Editorial / disponibilidade / software
    "Indie",
    "Casual",
    "Free to Play",
    "Early Access",
    "Utilities",
    "Software",
    "Education",
    "Tutorial",
    "Animation & Modeling",
    "Audio Production",
    "Design & Illustration",
    "Video Production",
    "Web Publishing",
    "Software Training",
    "Game Development",
    "RPGMaker",
    "GameMaker",
    "Benchmark",
    "Photo Editing",
    "360 Video",

    # Estilo visual / acabamento / humor / musica
    "Atmospheric",
    "Funny",
    "Cute",
    "Colorful",
    "Dark",
    "Stylized",
    "Realistic",
    "Minimalist",
    "Hand-drawn",
    "Cartoony",
    "Cartoon",
    "Abstract",
    "Beautiful",
    "Voxel",
    "Retro",
    "Old School",
    "Classic",
    "1990's",
    "1980s",
    "Pixel Graphics",
    "Anime",
    "Memes",
    "Psychedelic",
    "Cinematic",
    "Soundtrack",
    "Music",
    "Electronic Music",
    "Electronic",
    "Rock Music",
    "Instrumental Music",
    "8-bit Music",
    "Ambient",
    "Snow",

    # Tema / lore / ambientacao
    "Fantasy",
    "Dark Fantasy",
    "Sci-fi",
    "Space",
    "Magic",
    "Historical",
    "Medieval",
    "Futuristic",
    "Post-apocalyptic",
    "Cyberpunk",
    "Military",
    "War",
    "World War II",
    "World War I",
    "Aliens",
    "Zombies",
    "Robots",
    "Demons",
    "Supernatural",
    "Mythology",
    "Lovecraftian",
    "Noir",
    "Steampunk",
    "Crime",
    "Conspiracy",
    "Gothic",
    "Western",
    "Pirates",
    "Ninja",
    "Martial Arts",
    "Assassin",
    "Dinosaurs",
    "Dog",
    "Cats",
    "Vampire",
    "Werewolves",
    "Horses",
    "Dragons",
    "LEGO",
    "Mars",
    "Submarine",
    "Naval",
    "Underwater",
    "America",
    "Rome",
    "Dungeons & Dragons",
    "Warhammer 40K",
    "Games Workshop",
    "Cold War",
    "Politics",
    "Political",
    "Political Sim",
    "Capitalism",
    "Faith",
    "Illuminati",
    "Superhero",
    "Vikings",
    "Spaceships",
    "Transhumanism",
    "Underground",

    # Narrativa / audiencia / identidade / tom
    "Story Rich",
    "Choices Matter",
    "Multiple Endings",
    "Choose Your Own Adventure",
    "Narration",
    "Narrative",
    "Dynamic Narration",
    "Drama",
    "Romance",
    "Mystery",
    "Detective",
    "Investigation",
    "Psychological",
    "Psychological Horror",
    "Emotional",
    "Philosophical",
    "Lore-Rich",
    "Conversation",
    "Text-Based",
    "Linear",
    "Short",
    "Replay Value",
    "Well-Written",
    "Silent Protagonist",
    "Villain Protagonist",
    "Female Protagonist",
    "LGBTQ+",
    "Mature",
    "NSFW",
    "Sexual Content",
    "Nudity",
    "Family Friendly",
    "Wholesome",
    "Cozy",
    "Hentai",
    "Movie",
    "Feature Film",
    "Documentary",
    "Based On A Novel",
    "Foreign",
    "Epic",
    "Experience",
    "Episodic",

    # Julgamento editorial / tom / dificuldade
    "Great Soundtrack",
    "Violent",
    "Gore",
    "Blood",
    "Relaxing",
    "Difficult",
    "Unforgiving",
    "Dark Humor",
    "Comedy",
    "Parody",
    "Satire",
    "Addictive",
    "Fast-Paced",
    "Time Attack",
    "Score Attack",
    "Quick-Time Events",
    "Moddable",
    "Mod",
    "Remake",
    "Sequel",
    "Crowdfunded",
    "Kickstarter",
    "Cult Classic",
    "Nostalgia",

    # Descritores amplos/ambiguos que atrapalham similaridade estrutural
    "Horror",
    "Open World",
    "Exploration",
    "Character Customization",
    "Procedural Generation",
    "Perma Death",
    "Top-Down",
    "Isometric",
    "Real-Time",
    "Real-Time with Pause",
    "Immersive",
    "Nonlinear",
    "Destruction",
    "Physics",
    "Combat",
    "Loot",
    "Parkour",
    "Bullet Time",
    "Time Manipulation",
    "Time Travel",
    "Split Screen",
    "Voice Control",
    "Farming",
    "Transportation",
    "Minigames",
    "Trivia",
    "Music-Based Procedural Generation",
    "Offroad",
}


# Conjunto de auditoria usado para responder no relatorio se ainda
# sobraram tags semanticamente erradas apos a limpeza.
NON_STRUCTURAL_AUDIT_TAGS = {
    "Story Rich",
    "Pixel Graphics",
    "Early Access",
    "Fantasy",
    "Anime",
    "Family Friendly",
    "Female Protagonist",
    "Relaxing",
    "Great Soundtrack",
    "Violent",
    "Horror",
    "Sci-fi",
    "Open World",
    "Exploration",
    "Retro",
    "Atmospheric",
    "Cute",
    "Colorful",
    "Comedy",
    "Mystery",
    "Cozy",
    "Superhero",
}
